name: phishing_man
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.2.2=py37_0
  - python=3.7.7
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - tensorflow
  - nltk
  - pandas
  - pip:
    - scikit-learn
    - urlextract